[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pipewire_python"
author = "Pablo Diaz & Anna Absi"
home-page = "https://github.com/pablodz/pipewire_python"
requires-python = ">=3.7"
description-file = "README.md"
classifiers = [ "License :: OSI Approved :: MIT License",
                "Intended Audience :: Developers",
                "Intended Audience :: Science/Research",
                "Natural Language :: English",
                "Topic :: Multimedia :: Sound/Audio :: Capture/Recording",
                "Topic :: Multimedia :: Sound/Audio :: Players",
                "Programming Language :: Python :: 3.7",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                ]


[tool.black]
line-length = 100
